#ifndef ARMRULELIB_GLOBAL_H
#define ARMRULELIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ARMRULELIB_LIBRARY)
#  define ARMRULELIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ARMRULELIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ARMRULELIB_GLOBAL_H
